#!/usr/bin/env sh

# Run phpStan
./vendor/bin/phpstan analyze
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com PHPSTAN. Arrume antes de continuar... 😉";
    exit 1;
fi;

# rodar os testes
./vendor/bin/sail artisan test --parallel | php
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com algum teste. Arrume antes de continuar... 😉";
    exit 1;
fi;

# Format any files changed
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    ./vendor/bin/sail pint "${FILE}" > /dev/null >&1;
    git add "${FILE}";
done;

exit 0;